scientist-softserv/webstore

pages/browse/index.js, pages/index.js, pages/services/[ware].js
- use the various loading components on the home, service and browse pages
https://user-images.githubusercontent.com/29032869/202032377-464bc175-a379-4fff-8956-b3f4508622da.mp4
=> 50-use-loading-components

pages/browse/index.js, pages/index.js, pages/services/[ware].js, utils/api/index.js, utils/api/services.js, utils/theme/colors.js, utils/theme/typography.js
refactor the utils folder again in prep for the request related api calls
=> Refactor utils

pages/_app.js, pages/browse/index.js, pages/index.js, pages/services/[ware].js, utils/api/fetcher.js, utils/api/index.js, utils/api/services.js, utils/configurations.js, utils/index.js, utils/theme/colors.js, utils/theme/index.js
refactored the `utils` folder per the commits below.
=> Refactor utils v2

utils/configurations.js
- sort requests by updated at in descending order
- https://stackoverflow.com/a/51758014/8079848
=> 48 sort requests

pages/_app.js, pages/requests/index.js, styles/globals.css, utils/configurations.js
- adds "initiate a new request" button component to request list page
- wraps all components with a center-content class to add a max width (this will be changed to a BS container after adding BS)
- changes the length of request item descriptions since there is now more space on the screen for them
https://github.com/scientist-softserv/webstore-component-library/pull/51
=> Request List layout

package.json, pages/_app.js, pages/browse/index.js, pages/index.js, pages/requests/index.js, yarn.lock
- Adds bs5
- Updates several classes to use the correct bs classes
=> Add Bootstrap 5

pages/_app.js, pages/requests/[id].js, pages/requests/index.js, pages/requests/new/[ware].js, pages/requests/new/index.js, utils/api/index.js, utils/api/user.js
=> Get current user

pages/requests/index.js
add back container that got removed as a result of merge conflicts
=> add the containers back for request list

utils/api/requests.js
- Writes the api call to get all SOWs
- will be used in the documents component on the single request page
=> sow api call for documents

utils/constants.js, utils/theme/globals.scss
https://github.com/scientist-softserv/webstore-component-library/issues/73
example with OG footer
example with Bootstrap footer
=> Provides body classes needed to stick the footer to the bottom

utils/api/configurations.js, utils/api/index.js, utils/index.js
- no code additions/deletions
- put the configurations file into utils/api because it is an api related file
=> move configurations

utils/api/configurations.js, utils/api/requests.js
- add the configure_status function for use when we look up a single request
- create the function that returns a single request
=> 70 errant request statuses

pages/requests/[id].js, utils/constants.js
- this pr is reliant on the code in #76 
- start pulling in data so we can render the status bar component on the request page
=> 49 single request page

pages/requests/[id].js, pages/requests/index.js, utils/api/configurations.js, utils/api/requests.js, utils/theme/variables.js
- can view a request's stats on the show page
- styling of entire page to come later
=> 49 single request page v2

pages/requests/new/index.js
- display the blank request form
- add TODOs for later
=> 64 new request page

pages/requests/[id].js, utils/api/base.js, utils/api/requests.js, utils/api/services.js, utils/api/user.js
- able to send a message to the supplier with and without attachments
- rename "api/fetcher" to "api/base"
- create the "posting" base function that will handle post requests
https://user-images.githubusercontent.com/29032869/207734130-000ef358-a879-4d8d-972e-2aee5f11ccd9.mp4
=> 73 enable sending messages

__tests__/api/configurations.test.js, pages/requests/[id].js, pages/requests/index.js, utils/api/configurations.js, utils/api/requests.js
- adds the document component on the SOW page
- configures documents to return to the SOW page
- linting
#49 
https://share.getcloudapp.com/nOu1DDWA
=> Single request page - SOW documents

next.config.js, package.json, pages/_app.js, pages/browse/index.js, pages/index.js, pages/requests/[id].js, pages/requests/index.js, pages/services/[ware].js, utils/api/configurations.js, utils/api/requests.js, utils/api/services.js, utils/api/user.js
- update commands to run lint on the pages and utils directories in dev and prod
- change snake cased configuration function names into camelcase
- change "getXXX" api functions to "useXXX" according to lint/swr rules
- https://nextjs.org/docs/basic-features/eslint#linting-custom-directories-and-files
- https://swr.vercel.app/docs/getting-started#make-it-reusable
=> update lint capabilities

pages/requests/[id].js, utils/api/configurations.js, utils/api/requests.js
- able to show messages between the supplier and client on a request
- filtering is basic until we resolve https://github.com/assaydepot/scientist_api_v2/issues/167
=> 49-single-request-page-messages

pages/requests/[id].js, utils/api/configurations.js
- linting and add a key to the errors
- return the id from the filtered messages
=> Console reported errors

utils/api/configurations.js
- add `normalizeHtmlDescription` to remove inline styles
=> normalize html description

pages/index.js
- return a slightly better error from the index page
=> update index error

utils/api/configurations.js
Return the correct info in the message request so messages can show attachments
https://github.com/scientist-softserv/webstore-component-library/issues/99
Component Lib PR: https://github.com/scientist-softserv/webstore-component-library/pull/103
=> Update message config

package.json, pages/requests/new/[ware].js, pages/requests/new/index.js, yarn.lock
- validates the request form
- uses bootstrap validation for ui
https://github.com/scientist-softserv/webstore/issues/106
https://share.getcloudapp.com/NQu4xYro
- we may need to revisit bootstrap validation after we bring in the dynamic json schema form
=> Form validation

pages/requests/new/[ware].js, pages/requests/new/index.js
- adds attachments to the initial state on the request forms
https://github.com/scientist-softserv/webstore-component-library/issues/106
https://github.com/scientist-softserv/webstore-component-library/pull/105
=> Add attachments

.eslintrc.json, pages/_app.js, pages/requests/[id].js, pages/requests/new/[ware].js, pages/requests/new/index.js, utils/api/configurations.js, utils/api/requests.js, utils/constants.js, utils/theme/variables.js
- add some more lint rules that are already defined in the library
- fix code that breaks the lint rules
=> More eslint rules

README.md, pages/services/[ware].js
Component Library Ticket
https://github.com/scientist-softserv/webstore-component-library/issues/120
Component Library PR
https://github.com/scientist-softserv/webstore-component-library/pull/121
=> Pass props to itempage so the button can go to the right place

pages/requests/new/[ware].js, utils/api/base.js, utils/api/requests.js
co-authors: @alishaevn, @summer-cook 
The user should be redirected to the request's page after they submit successfully
https://share.getcloudapp.com/p9uLZQlO
- error handling
- proposedDeadline cannot be null - even though there is an option for it to be null in the marketplace
- submitting on a blank request still needs to be handled
=> 93 - Redirect to the request's page after submitting new request

pages/requests/new/[ware].js, pages/services/[ware].js, utils/api/requests.js
- set the description and timeline for a blank request
- pass the id correctly again to the boostrap form. fix spacing
=> 93 blank request

utils/api/configurations.js, utils/api/requests.js
- properly handle there being no proposed deadline on a request page
=> 93-handle-null-proposed-deadline

pages/requests/[id].js, utils/api/requests.js
we've been able to send messages for several weeks now, but it turns out that the way we're handling it is working by accident. reference: https://assaydepot.slack.com/archives/C03FZDALABG/p1674670706033099?thread_ts=1674590788.830039&cid=C03FZDALABG
until we have decided on a direction in #156, I'm stopping us from being able to send messages at all so they don't go to the incorrect place.
=> 156 stop sending messages

utils/api/requests.js
- uses the dynamic forms array vs. the object
Closes #151
=> use dynamic forms instead

pages/index.js, utils/api/requests.js, utils/theme/theme.module.scss
co-author: @alishaevn 
co-author: @summer-cook 
we've been updating both the webstore and component library over the past 2 days and I think some of our code one of us is doing in one repo has interfered with what the other was doing in the other repo. we got on tuple and worked through these things together to get back to a good spot.
=> 166 more item loading

pages/browse/index.js, pages/requests/[id].js, pages/requests/index.js, pages/requests/new/[ware].js, utils/api/requests.js, utils/api/services.js
as a signed in user, no api calls were returning data. with this pr, they will
- the github ui would not let me revert #159, so I am doing it manually. now that we always have an access token that belongs to the provider or the user, we do not need to check for the existence of one. which means we do not get stuck in loading because the api is using a "null" value
- only conditionally check for api params that are not the access token
- return the loading component first so the page does not glitch for a signed in user
https://user-images.githubusercontent.com/29032869/216103654-135396ef-df64-46e5-b68c-a84d8b3795f6.mp4
=> 161 restore api calls

.github/issue_template.md, .github/pull_request_template.md
Adds 2 .md files: a Github issue template and a PR template
=> add github issue and pr templates to repo

package.json, yarn.lock
- patch version bump to `0.1.7`
- update the wcl to `v0.1.14`
=> Patch version bump 0.1.8

pages/requests/[id].js, pages/requests/[uuid].js, utils/api/requests.js
adds mutate to Files so newly uploaded attachments will appear more quickly/without refreshing in the View Files pane
Refs https://github.com/scientist-softserv/webstore-component-library/issues/152
new files only showed up on page refresh
new files will show up more quickly
=> 152- add attachments from viewfiles - mutate files

.github/workflows/deploy.yml
adds deployment workflow to main
=> add-deploy-to-main

cypress/e2e/requests.cy.js
- refactors to use switch case
- brings back the error test & makes it pass by making useDefaultWareID throw an error as well
=> refactor to use switch case & fix error test

.editorconfig
the idea of an editor config is nice overall. however, I've realized that my config and summer's conflict on some things (like trailing spaces), so this should help out in that regard.
- first draft of the editor config
- 
<details>
<summary></summary>
</details>
=> add an editor config

pages/requests/[uuid].js, utils/api/configurations.js, utils/api/requests.js
refactor of #254 
_I'm not sure why that quick error notice shows up when going back to view the browse page. will double check if it's still there after we switch to the beachside vendor with the appropriate permissions_
https://user-images.githubusercontent.com/29032869/223574402-142ee474-61ee-419f-8166-4d660f6216d0.mp4
=> 138 display pos refactor

pages/index.js, utils/constants.js
a dev improvement
- more explicit constant names for the home page
- make the app title a constant
=> better constant names

pages/api/auth/[...nextauth].js, pages/requests/[uuid].js, utils/api/configurations.js, utils/api/requests.js
co-author: @alishaevn 
rel: #260 
- adds an async get/use request for POs
- calls this request via a useEffect in the uuid file
- adds properties that need to be shown on each PO to the configurePOs method
Refs #138
- could not get data for POs on the uuid page for the webstore
- can get data for POs on the uuid page
(component library changes need to be made to show all the correct data)
https://share.getcloudapp.com/Kou9yNOk
This needed to be done with async functions vs. useSWR because multiple api calls needed to happen on an  array of PO IDs, which was determined by a different api call. This can be done more cleanly/with swr once useSWRList is added the swr repo, but this feature is still in development
=> 138 diplay POs

pages/browse/index.js, pages/requests/[uuid].js, utils/api/requests.js
- noticed during testing that there is no message that says "no results" in the search
Refs #269
- user performs a search without results and it just shows a blank page
- the ui tells the user that their search returned no results
https://share.getcloudapp.com/4guN7BrL
=> No results message

README.md, package.json, yarn.lock
use the newly released `0.1.16` version of the wcl
- the app still works as expected with the component updates
=> Upgrade wcl

utils/api/services.js
an additional ware was added to the bbs org, but it wasn't showing up on the browser page. this change fixes that.
- we were missing a ware
- return all wares for the org
<details>
<summary>ngs: next generation sequencing</summary>
</details>
=> return all wares

pages/api/auth/[...nextauth].js
signing in was failing in local dev
- able to sign in on dev again although there are no webhooks
=> 135 no webhooks in dev

package.json, yarn.lock
bump @scientist-softserv/webstore-component-library to 0.1.17
=> bump wcl to v0.1.17

utils/api/requests.js
refs #295 
- only attach files if there are any
- use the right url to get the quotedWareID
=> 295 create request without attachments

pages/privacy-policy/index.js, pages/privacy-policy/scientist-privacy-policy.js, utils/constants.js
- bring in the commit from https://github.com/scientist-softserv/phenovista-digital-storefront/pull/12
- update the privacy policy to be generic
- update existing links so they don't go to nonexistent pages
- #313
=> 311 scientist privacy policy

pages/terms-and-conditions/index.js, utils/constants.js
add the terms and conditions page
add a page that can be updated with client specific terms and conditions
=> 314 terms and conditions

pages/terms-of-use/index.js, utils/constants.js
add the terms of use page
add a page that can be updated with client specific terms of use
=> 315 terms of use

utils/constants.js
- Adds an example & comment to the constants for when we want a link to open in a new tab
- Ticket: https://github.com/scientist-softserv/phenovista-digital-storefront/issues/15#issuecomment-1812628109
- Webstore compoent lib PR: https://github.com/scientist-softserv/webstore-component-library/pull/196
- Phenovista PR:
=> Add comment and example for external link

package.json, yarn.lock
Updates version of the webstore component library
=> update wcl to v0.1.18

utils/api/configurations.js, utils/theme/globals.scss
successfully displaying checkboxes on the request form!
- #329 
- checkbox fields show!
- the "other" input put is conditional on the value of the checked boxes above it. [sherman said ](https://assaydepot.slack.com/archives/C03FZDALABG/p1701465876404399?thread_ts=1701372621.389769&cid=C03FZDALABG)that phenovista does not have any conditional fields though, so it's not blocking this work from being merged. I will work on that feature in a separate pr.
=> 329 dynamic form checkboxes

.env, package.json, pages/_app.js, yarn.lock
contribute back the changes from https://github.com/scientist-softserv/phenovista-digital-storefront/pull/37
=> add google tag manager

.env, charts/webstore/templates/deployment.yaml, charts/webstore/values.yaml, ops/production-deploy.tmpl.yaml, ops/staging-deploy.tmpl.yaml, pages/_app.js
contribute back more changes related to https://github.com/scientist-softserv/phenovista-digital-storefront/issues/36
- wiki doc: https://github.com/scientist-softserv/webstore/wiki/Analytics#google-tag-manager
=> Update charts for google tag manager

README.md
=> better readme cleanup

README.md
readme updates after onboarding a new dev
=> better-readme-v3

pages/requests/new/[ware].js
Refs #344 
Adds the ware.snippet to the new request form
no description appeared on the new request form
the snippet appears on the new request page
=> I344 ware detailed descriptions

package.json, yarn.lock
Updates the wcl to its latest release, 0.1.21
=> Update webstore component library to 0.1.21

package.json, yarn.lock
upgrade the webstore component library to bring in new changes
- ref: https://github.com/scientist-softserv/webstore-component-library/releases/tag/0.1.22
=> upgrade the wcl to `v0.1.22`

package.json, yarn.lock
upgrade wcl to bring in some updates.
=> upgrade the wcl to `0.1.23`
