scientist-softserv/webstore

- utils/api/requests.js
the statuses shown on "/requests" are also configured to follow the same rules as the statuses on individual request pages
- the browser shows the configured status
- the console array shows the original status
> 70-configure-statuses-for-requests-page

- pages/requests/[id].js
- utils/api/configurations.js
- status bar colors correctly indicate the current status again
| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/208769039-830c0a79-98e5-49d1-9cd1-17d12230b70d.png) | ![image](https://user-images.githubusercontent.com/29032869/208769103-de10ff83-66f9-44c8-b939-62e9a4e7fe51.png) |
> 94 fix status bar colors

- pages/requests/[id].js
- accounting for when there are no documents to display on a request
> 96 documents refactor

- pages/requests/new/[ware].js
- pages/requests/new/index.js
- create the new request forms in the webstore instead of in the library
- requires the [refactored blank request page](https://github.com/scientist-softserv/webstore-component-library/pull/102) from the library
- both request pages still exist because I'm a little unclear on how this `/make-a-request` api endpoint and default_ware value are going to work.
> 64 new request pages

- package.json
- yarn.lock
after merging the [CI code](https://github.com/scientist-softserv/webstore/pull/120) into the [request form pr](https://github.com/scientist-softserv/webstore/pull/119)...the request pages would no longer load. seems like the `ajv` dependency wasn't getting recognized anymore for some reason. rjsf worked before the CI code came in. idk for sure what about the ci code changed it.
one thing that may have been the cause is the following code was added to the `package.json` file. previously we were using node `v16.14.0`
``` js
"engines": {
"node": "^19.2.0"
}
```
<details>
<summary>pic of the ajv error</summary>
</details>
- install `ajv` as a full dependency so the new request page loads
> fix the ajv dependency

- package.json
- yarn.lock
related to #121 
after merging the above pr, others who pulled down the latest code still got the same error I was getting then and couldn't build the app. at the time I added `ajv`, but this is a more complete fix and feels better. after the steps below I confirmed that I could still successfully run `yarn dev` and load both a blank and dynamic request form. I can also successfully run `yarn build`.
``` bash
yarn remove @rjsf/core @rjsf/utils @rjsf/validator-ajv8 ajv
yarn add @rjsf/core @rjsf/utils @rjsf/validator-ajv8
```
> ajv dependency pt2

- utils/api/requests.js
- stop showing the blank request form before the dynamic one loads
- when the user checks the box that says there isn't a proposed deadline the following is sent as part of the api `create` call
``` js
no_proposed_deadline: true
proposed_deadline_str: ""
```
> 93 no proposed deadline

- README.md
- package.json
- yarn.lock
- update the node engine to `18.13.0`
- delete yarn.lock
- delete node_modules
- `yarn`
- update the wcl to v0.1.10 to be node compliant
- update the readme to reference using the correct node version
~@xrl  I had to delete the library from the package.json file to get `yarn` to complete (I didn't commit that). I can't seem to reinstall the library because it still wants node v19.2.0. I can't figure out where or why that is. ideas?~
> change node to 18

- pages/index.js
- utils/constants.js
- changes the path on the featured service page to point to the new request page for that service
- adds a constant for that path & comments of how to use the service page instead if the user decides
> 131 hide featured service page

- pages/requests/[id].js
- pages/requests/index.js
- pages/requests/new/[ware].js
- pages/services/[ware].js
- adds mt-5 on al loading components so the spinner is not obscured by the header
https://share.getcloudapp.com/2Nu68RgL
> loading spinner margin

- pages/requests/[id].js
- utils/api/requests.js
- handles attachments on the request form
- renames sendMessage to postMessageOrAttachment because the notes endpoint is used for both request messages & request attachments
creating a request, and then checking the notes endpoint to make sure the attachments are there
https://share.getcloudapp.com/Z4um9bLb
included this info in a comment as well to further explain how "notes" are used:
- in the scientist marketplace, both user messages sent on a request's page and attachments to a request of any kind are referred to as "notes"
- only user messages will have a `body`, attachments to requests will not.
- only attachments that are added when creating a new request should have a `title` & `status`.
> 128 - get attachments working

- pages/requests/[id].js
- utils/api/requests.js
- uses SWR mutate to make the messages update after a new message is submitted
https://share.getcloudapp.com/Z4umNGzb
- the messages are still not instant- just faster, possibly due to the api calls lagging a little bit. if these messages needed to update in near-real time, we could use the [refreshInterval setting of useSWR](https://swr.vercel.app/docs/revalidation#revalidate-on-interval)- we decided not to go this route since it would force api calls every few seconds, and since this is not a chat feature, it was not deemed necessary to have completely instantaneous updates
> 139 faster message viewing

- pages/browse/index.js
- pages/index.js
- pages/requests/[id].js
- pages/requests/index.js
- pages/requests/new/[ware].js
- pages/services/[ware].js
- utils/api/configurations.js
- utils/api/requests.js
- utils/api/services.js
We are using the more reusable `Notice` component to render our errors and other alerts.
_after I pulled in main...every api request stays in "loading". this is because the url being used in all of our `swr` functions remains at null, instead of updating when the access token or other property is defined. I'll handle that in a different ticket._
_ticket related to the above issue: https://github.com/scientist-softserv/webstore/pull/159_
_new ticket to handle the above issue: https://github.com/scientist-softserv/webstore/issues/161_ 
|"/" | "/requests" |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/29032869/215129421-719cad76-703e-4c73-8ba4-3da33497f85d.png) | ![image](https://user-images.githubusercontent.com/29032869/215129708-e2be9f6e-9692-491d-84e9-eb5a645a06ee.pn …
> 132 restrict request routes

- utils/theme/theme.module.scss
adds 2 variables to the theme map for use throughout the app. utility classes for these colors will be automatically generated by bootstrap (for example, we can now use bg-light-2)
https://github.com/scientist-softserv/webstore-component-library/issues/139
Component Library PR: https://github.com/scientist-softserv/webstore-component-library/pull/140
> 139 add variables to theme map

- .env
- README.md
- utils/api/base.js
- utils/api/configurations.js
a non logged in user ought to still be able to access the "/" and "browse" routes.
- add the supplier credentials as a fallback if the user is not signed in
the following was removed from the `.env` file in favor of the `.env.local` file.
``` bash
```
- https://assaydepot.slack.com/archives/C03FZDALABG/p1669679901998389?thread_ts=1669679800.623529&cid=C03FZDALABG
- https://www.rubydoc.info/gems/httpauth/0.1/HTTPAuth/Basic#pack_authorization-class_method
- https://dev.to/danroe/comment/1p98g
- https://mixedanalytics.com/tools/basic-authentication-generator/#what
> 67 without authenticated user

- pages/requests/index.js
since the outer wrapper of the LinkedButton component is an a-tag, it should not be full width or else the link will span the full width as opposed to just being on the button. this pr fixes that
Closes #184 
Closes 
https://share.getcloudapp.com/yAuAEjvB
> 184 make only the button clickable

- utils/api/configurations.js
- utils/api/requests.js
- utils/api/services.js
**there are no code changes here. just moving functions around for better organization.**
- move the dynamic form related functions from "/api/requests" to "api/configurations"
- rename them so that they start with the "configure" keyword
- structure "api/requests" and "api/services" by their http request method type
> Restructure utils

- pages/requests/[id].js
- utils/api/configurations.js
- utils/api/requests.js
- updates variables to semantically include both messages & files, since these both are accounted for by the notes endpoint
- creates a configure files method so that the attachments are returned as a single array vs being nested to make the viewfiles component simpler.
- returns both files and messages as variables to be used in the `pages/requests/[id].js` page & passed to respective request page components
component library pr: https://github.com/scientist-softserv/webstore-component-library/pull/150
ticket: https://github.com/scientist-softserv/webstore-component-library/issues/134
- should not be merged until related component library pr is merged.
> 134 show attachments

- utils/api/requests.js
updates the initialize endpoint in the webstore to account for the changes in https://github.com/assaydepot/scientist_api_v2/issues/210
new request page should load in staging env
ref #206
> update initialize endpoint

- utils/api/requests.js
the uuid is needed to send messages/attachments, and this lives on the `quoted_ware_refs`. Webstore users will need the option to send an attachment during creation of the request, but quoted_ware_refs are not being added until a proposal is created. This can be added sooner by passing the provider_id during request creation.
Closes https://github.com/scientist-softserv/webstore/issues/208
newly created request:
in postman:
> Add a provider_ids array to the create request params

- pages/requests/[id].js
- utils/api/configurations.js
- utils/api/requests.js
uses the new messages endpoint to filter the messages on the request page `/quote_groups/${requestUuid}/messages.json`
Closes #110 
all messages would show on the request page
the internal messages will be filtered out on the request page (for instance: "username has initiated the request")
<details>
<summary>Request with no messages in webstore- internal messages no longer appear automatically</summary>
</details>
<details>
<summary>Request with messages in webstore</summary>
</details>
> use new endpoint to filter messages

- pages/requests/[id].js
- utils/api/base.js
- utils/api/configurations.js
- utils/api/requests.js
brings back the ability to send messages, and adds the quotedWareID to the request so it can be passed in the post message request as well as in the posting method since it needed to be used when adding initial attachments
Ref #156 
messages could not be sent from the webstore, and were sent with the incorrect param of quote_group_id vs the ID of the quoted_ware.
> 156 refactor sending messages

- cypress/e2e/browsing.cy.js
add 2 tests for browsing on the browse page. edit 1 test to include 'q' in the test's url
Refs #210
I added 2 tests in `cypress/e2e/browsing.cy.js`:
1. a user conducting a blank search on /browse
2. a user conducting a queried search on /browse
I also edited a pre-existing test on line 30 of `cypress/e2e/browsing.cy.js`:
- this test did not include the `q` in the URL for `cy.url().should('include', '/browse?q=next')`. On my local test runs, omitting the `q` from `'/browse?q=next'` led to a failure.
1. /browse did not have tests for searching on `browse`
2. Line 30 test failed
1. /browse has 2 tests for searching on `browse`
2. Line 30 test passes
<details>
<summary>Line 30 test: before and after I added 'q' to line 30's test's URL</summary>
</details>
Please let me know if my change to …
> 210-search-on-browse-tests

- pages/requests/[uuid].js
- utils/api/configurations.js
when looking at a request show page in the webstore, the current url is "/requests/:id". this is because we do not have access to a uuid from the /quote_groups/mine.json endpoint. in order to align with the marketplace, we want the url to read "/requests/:uuid" instead.
- requests were referenced by their id on the show page
- update the request href to use the uuid
- rename the [id] file to [uuid] since that is the value we are now basing the page on
- update the value of "href" in the "configureServices" function to pass an object with "pathname" and "query" values for consistency with other links in the app
https://user-images.githubusercontent.com/29032869/220400768-fb9295af-7aec-4237-afcd-bd36be5660d2.mp4
> 171 request uuid

- utils/api/requests.js
- the actions group component would error when `files` was undefined
<details>
<summary>files error</summary>
</details>
- make sure that `files` is at minimum an empty array on the request page. this accounts for the loading phase too. also makes sure the `filter` array method in actions group does not err out
- view a request show page
- click the "view files" action
> always define files

- pages/requests/[uuid].js
- pages/requests/new/[ware].js
- utils/api/base.js
- utils/api/configurations.js
- utils/api/requests.js
I noticed some areas for improvement that may also help our future selves while working on #226 
- simplify `posting` so it is easier to use in other use cases in the future
- change the prop name passed into `createRequest` from "data" to "dynamicFormData" to remove conflicts after updating `posting`
- only try to attach files to a new request if there are any. also, account for attachment errors
- account for errors on the new request page and refactor for the new return values from `posting`
- an empty object is still truthy. check that the error has data in `configureErrors`
- checking that an array has length instead of if the length does not equal 0 (same thing, little less code)
<details>
<summary></summary>
</details>
> 143 refactor creating requests

- utils/api/requests.js
- we couldn't attach files when creating a request
- send the access token to `createMessageOrFile` from `createRequest`
<details>
<summary></summary>
</details>
> 143 send acccess token

- pages/requests/new/[ware].js
initiating a request makes 3 different api calls, so it takes a few seconds to transition to the next page. we should disable the button when clicked so a user doesn't click it multiples times thinking that the first didn't go through.
Refs #230 
user was able to click the initiate request button several times while the submit method was running, and it would cause duplicate requests
after the button is clicked, it is disabled and the page is loading until the newly created request's page pops up
Video: https://share.getcloudapp.com/nOuKz9BN
> 239 page loading after request creation + disable button

- pages/api/auth/[...nextauth].js
- utils/constants.js
- we were not handling the refresh token
- create the `refreshAccessToken` function to be used if a user's access token is expired
- create a local variable to determine the timeout period
- we will use the api value from https://github.com/assaydepot/rx/issues/21497 instead in the next phase
- https://next-auth.js.org/tutorials/refresh-token-rotation
- [def refresh_token](https://github.com/assaydepot/rx/blob/c5f006b70f26a77f180e6941101fdc2b39e3d7f1/app/controllers/oauth_controller.rb#L134-L150)
- [old oauth pr](https://github.com/assaydepot/rx/pull/9551)
- https://codezup.com/3-ways-to-base64-string-encode-decode-javascript-node-js/
- https://curl.se/docs/manpage.html
- https://github.com/axios/axios#using-applicationx-www-form-urlencoded-format
> 232 refresh token

- cypress/e2e/requests.cy.js
- cypress/support/commands.js
- cypress/support/e2e.js
- refactor api intercept function to be a cypress custom command, and use in requests.cy.js
- intercept needs to be added as many times as the number of api calls exist on a page, so it was getting long. this will help us avoid rewriting repetitive intercepts for every page of tests
- also moves the scientistApiBaseURL variable since it will likely be used throughout most of the e2e tests
- can use scientistApiBaseUrl variable
- can use customApiIntercept cypress command
> Refactor api intercept function

- .npmrc
- README.md
- package.json
- yarn.lock
ref: https://github.com/scientist-softserv/webstore-component-library/issues/172
the webstore component library (wcl) package we published from the repo requires a personal access token to be installed. (github requirement) we've been doing this locally, but publishing to vercel causes a security concern. so, I published the wcl to npmjs.com instead.
- we were using the (now deleted) github registered package version of the wcl
- switch to using the webstore-component-library from npmjs
- removed the `.npmrc` file so we are not looking in the github package registry
- remove reference to the github package in the readme
> 172 switch to npmjs

- utils/api/requests.js
I'm not sure why, but sometimes our data does not have the "quoted_ware_refs" property on it. a search for the request in postman however, returns the property.
- sometimes a newly created request does not return the quoted ware, so creating the attachments fails
- add a fallback for "data.quoted_ware_refs?.[0]?.id" when creating a request with attachments
> 143 check for ware ref

- README.md
- remove the outdated step about using a github token to pull the wcl
- formatting
> readme update for wcl part 2

- next.config.js
deploying #276 main caused [build errors](https://vercel.com/scientist-softserv/webstore-staging/EFZNfjPd4UQQqpCYocRGc4JpX3WA) on the vercel prod branch. I created a new account auth token with the appropriate scopes according to the [config docs](https://docs.sentry.io/product/cli/configuration/), but then I got a different vercel [build error](https://vercel.com/scientist-softserv/webstore-staging/7nYbBCQS7ayqcBQC9ARvoDqPPLU1).
I'm removing the setCommits config option for now. I may add it back at a later date when I have time to debug.
- https://charles-stover.medium.com/how-i-debugged-sentry-release-no-commits-found-change-commits-range-d390ba4e326c
> more sentry changes

- utils/api/configurations.js
the sales team would like a more complicated request form for the demo. some of the more complex forms include array property's which are currently not accounted for in the mvp app. this change will hide those properties until another phase of work where we can make that happen.
- hide properties that have an array type from the dynamic form
> hide arrays from dynamic form

- utils/api/requests.js
how we find the default ware is different for the beachside biotech org. this change may reflect how all new org's that only represent a single provider are created. we'll have to double check that when the next org is created however.
Refs #issuenumber
- we were not returning the default ware id
- we're returning the default ware id
> fix the default ware

- utils/api/requests.js
- utils/api/webhooks.js
related: https://github.com/scientist-softserv/webstore/pull/168
- check for access tokens before making request or webhook related api calls. 14k related sentry errors for "No access token provided."
- using `accessToken` for all calls regardless of other args since the accessToken is what fails. also, none of the other arguments seem to throw errors.
- add comment referencing https://github.com/assaydepot/scientist_api_v2/issues/251
<details>
<summary>expected flow through the app</summary>
- unsure why the favicon sometimes can't be found immediately. that's not an api error though
- also unsure why the promo image has issues sometimes. the `/ware` endpoints don't require a user specific access token though so it's also unrelated to these changes
- the 301 moved permanently error for …
> 292 reduce sentry errors

- pages/api/auth/[...nextauth].js
only users signing in with oauth get the email webhook set up
- users who are re-authenticating with their refresh token get email webhooks too
> 135-set-webhook-in-refreshAccessToken

- .env
while testing email webhooks last friday:
> I signed out and back in to the staging site. I then created a new request and sent a proposal from the backoffice. the email I received is below. in clicking the link I was routed to the webstore, but given a "Did Not Connect: Potential Security Issue" error.
> the link to my created request is: https://webstore-staging.vercel.app/requests/c98ac1b9-9b91-467a-b5b7-24c9fc65659a
the link that I was redirected to from the email is: https://www.webstore-staging.vercel.app/requests/c98ac1b9-9b91-467a-b5b7-24c9fc65659a
> looks like the email added "www" to the url. once I removed the "www" from the url, I was taken to the correct request with an sow.
- remove "www." from the `NEXT_PUBLIC_APP_BASE_URL` so that the emails get redirected correctly
> 135-fix-base-url

- next.config.js
conditional sentry exception handling
clients ought to have the option to use whichever exception handler they want, not only sentry. by default, the apps that are set up by softserv will use sentry however. this change allows the app to still build whether the sentry values in .env.local are set or not. whether that means the app will use something other than sentry, or the sentry project has not been set up yet
related:
- https://github.com/scientist-softserv/phenovista-digital-storefront/issues/5
<details>
<summary>the build failed</summary>
</details>
<details>
<summary>the build succeeds</summary>
</details>
> sentry conditionally

- utils/api/requests.js
restore ability to look at individual requests again.
this change is necessary because of the change in PurchaseOrdersController#index in commit 71077c6 of the api.
- #308 
- trying to map over a hash (which was previously an array) was throwing an error
<details>
<summary>error</summary>
</details>
- the data is properly being found
> 308-unable-to-view-requests

- pages/privacy-policy/index.js
- pages/terms-and-conditions/index.js
- pages/terms-of-use/index.js
#311 
while working on https://github.com/scientist-softserv/phenovista-digital-storefront/issues/10 I realized that passing just a string as the text did not give a good user experience. I wrote up directions on how to instead convert a word doc to javascript so we can more easily mimic the original file.
> 311 updates to the legal policies

- utils/api/services.js
- utils/constants.js
- #327 
return all wares for the given marketplace
the default api setting is to return 25 wares per page. so, we were only returning 25 wares total on the browse page. we now are returning "all" wares by choosing to get 2000 wares per page in the api request. I didn't see a way to set `page: "all"` or `per_page: "all"`.
if a marketplace has more than 2000 wares, we will need to increase the number.
<details>
<summary> postman api call</summary>
</details>
https://github.com/scientist-softserv/webstore/assets/29032869/278594d7-2e05-42da-a1ff-304578b12f27
> 327 browse all wares

- pages/_app.js
- pages/requests/[uuid].js
- pages/requests/index.js
- pages/requests/new/[ware].js
- #325 
correctly block unauthed users from pages that require auth
previously, a page that required authorization would show the spinning modal indefinitely, instead of showing the message that informs the user they must be signed in. this is because the variable that determined whether the spinner should show, always remained true.
this commit breaks out the logic to first check if there is a user. what renders on the page is based on that.
checking for the presence of a session has to come after all of the hooks so we don't violate the react-hooks/rules-of-hooks rule. ref: https://legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level we return the loading state in two different locations because it's rendered based on separate conditions. when isLoading is true …
> 325-unauthed-experience

- pages/_app.js
- pages/legal-notices/cookie-policy.js
- utils/cookies.js
update the cookie policy to reflect webstore cookies
ref: https://assaydepot.slack.com/archives/C05U031L0V9/p1701809599298789?thread_ts=1701363833.246969&cid=C05U031L0V9
- the cookie policy wording has been updated to account for info that's specific to the webstore
- the option to enable/disable cookies is hidden altogether since we only have essential cookies right now
to see the full coolie policy, refer to "/legal-notices/cookie-policy" on the vercel preview site below!
> 316 more cookies

- pages/requests/[uuid].js
- utils/api/configurations.js
- utils/api/requests.js
restore ability to view/create purchase orders.
changes were recently made to the purchase orders serializer. this commit updates our code so the app continues working with that change.
currently, we haven't experienced any issues because the singular version of the endpoints referenced in the ticket below still exist. we are transitioning to the plural versions however so that the singular versions can be removed.
> 337 api changes

- cypress/fixtures/one-request/files.json
- cypress/fixtures/one-request/messages.json
- utils/api/requests.js
removed the `site` property from the request object because it erred in the API (ref: [slack thread](https://assaydepot.slack.com/archives/CF6490Y80/p1705017664697359?thread_ts=1704996805.983419&cid=CF6490Y80))
- #342 
- we are able to create requests once more
https://github.com/scientist-softserv/webstore/assets/29032869/3948089c-df1c-406e-90c4-68f90313ba61
> 342 unable to create requests

- pages/requests/new/[ware].js
- utils/api/requests.js
- utils/theme/theme.module.scss
The request form should display both for logged in and logged out users. For users who are logged out, the form and button should be disabled. 
- #345 
- Component library PR: https://github.com/scientist-softserv/webstore-component-library/pull/202
Before this PR, a user clicked on a ware to make a request, and they would end up at a page with just a notice that said "Unauthorized"
After this PR, when a logged out user clicks on a ware to make a request, they are able to see the form to make the request, but it is disabled. They can also see a notice at the top of the form prompting them to log in if they would like to fill it out. 
If the user is logged in, they should still be able to fill out the form and submit requests. 
Video: https://share.zight.com/NQuBr6Bx
<details>
<summary> …
> Show disabled form for logged out users

- package.json
- pages/browse/index.js
- utils/api/configurations.js
- utils/helpers.js
- yarn.lock
Gets markdown working on the browse page. Homepage will still use snippets. 
- Component Lib PR: https://github.com/scientist-softserv/webstore-component-library/pull/206
- Ticket: https://github.com/scientist-softserv/webstore-component-library/issues/205
- As a user, I would not see markdown in descriptions on the browse page that contain markdown
- As a user, i will see markdown in descriptions on the browse page that contain markdown
-  As a user, I will see snippets on the featured service page, and descriptions on the browse/search page. 
<details>
<summary>Browse page will use description with markdown</summary>
Video: https://share.zight.com/o0uOqZx2
</details>
<details>
<summary>Featured services will still use snippet</summary>
</details>
> Get markdown working on browse pages

- package.json
- pages/browse/index.js
- yarn.lock
Some ware descriptions have a mix of markdown & html. This PR adds a plugin to the existing `react-markdown` plugin to account for times where this is the case. 
- https://github.com/scientist-softserv/webstore/issues/368
- descriptions with html would render the html as text
- descriptions with html will convert the html to html
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Render html with react-markdown rehype-raw plugin

- .env
the `.env` was added to gitignore a few weeks ago. it is still being tracked however, because it once was. with this commit, we should no longer be tracking it.
- ref: https://stackoverflow.com/a/53431148/8079848
> untrack file in .gitignore

- cypress.config.js
- cypress/e2e/browse.cy.js
- cypress/e2e/home.cy.js
- cypress/fixtures/services/filtered-wares.json
- cypress/support/commands.js
- utils/api/base.js
fix the 7 home specs  **locally**. they will still fail in ci due to configuration. (ref: #378)
- #361 
1. pull this branch
2. ensure you have all of the environment variables in the `env` property of "cypress.config.js" set up.
3. run `yarn cypress:e2e`
4. choose the "home" test
> 361 fix home specs

- pages/requests/new/[ware].js
Linking to the sign in page on a disabled request form
instead of only displaying text in the notice we converted the text 'please log in' to be a clickable link to log in 
- issue #383
> 383-update-disabled-request-message

- utils/api/base.js
able to log in again
the `signIn` function from "next-auth/react" uses `fetcher` and returns a 404 error response. throwing that error causes an `OAUTH_CALLBACK_HANDLER_ERROR`, which prevents users from signing in. `signIn` doesn't pass a url to `fetcher`. the check below ensures that other errors still get thrown
- ref: https://github.com/scientist-softserv/webstore/issues/321
https://github.com/scientist-softserv/webstore/assets/29032869/d0aaa6b6-df1e-48cd-a2d9-9607e4ee93c1
> 321-restore-login
